Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 60

Database:
  DBType: postgres
  Username: postgres
  Password: 12345678
  Host: localhost
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  PrseTime: True
  Port: 5431

JWT:
  Secret: Jack
  Issuer: blog_service
  Expire: 7200

Email:
  Host: smtp.google.com
  Port: 465
  UserName: xxxxxx@gmail.com
  Password: xxxx
  IsSSL: True
  From: xxxxxxxx@gmail.com
  To:
    - xxxxxxxx@yahoo.com.tw