Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: postgres
  Username: postgres
  Password: 12345678
  Host: 127.0.0.1:5431
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  PrseTime: True
  Port: 5431